before:
  hooks:
    - go mod download
builds:
  - id: "owncast"
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
    binary: owncast
    flags:
      - -trimpath
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      # - freebsd
      # - openbsd
      # - darwin
      # - windows
    goarch:
      - amd64
      # - arm64
      - 386
      # - arm
    goarm:
      - 6
      - 7

archives:
  - id: default
    builds:
      - owncast
    # format_overrides:
    #  - goos: windows
    #    format: zip
    replacements:
      # windows: Windows
      # darwin: Darwin
      386: i386
      amd64: x86_64

nfpms:
  - builds:
      - owncast
    vendor: owncast
    homepage: "https://owncast.online/"
    maintainer: "Christian Muehlhaeuser <muesli@gmail.com>"
    description: "Owncast streaming server"
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

brews:
  - goarm: 6
    tap:
      owner: owncast
      name: homebrew-tap
    commit_author:
      name: "Christian Muehlhaeuser"
      email: "muesli@gmail.com"
    homepage: "https://owncast.online/"
    description: "Owncast streaming server"
    # skip_upload: true

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
