# See https://owncast.online/docs/configuration/ for more details

instanceDetails:
  name: Owncast
  title: Owncast
  summary: "This is brief summary of whom you are or what your stream is. You can read more about it at owncast.online.  You can edit this description in your config file."

  logo:
    small: /img/logo128.png
    large: /img/logo256.png

  tags:
    - music
    - software
    - streaming

  # https://owncast.online/docs/configuration/#external-links
  # for full list of supported social links.  All optional.
  socialHandles:
    - platform: github
      url: http://github.com/owncast/owncast
    - platform: mastodon
      url: http://mastodon.something/owncast

videoSettings:
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: abc123

yp:
  # Enable YP to be listed in the Owncast directory and let people discover your instance.
  enabled: false
  # You must specify the public URL of your host that you want the directory to link to.
  instanceURL: http://yourhost.com
