instanceDetails:
  name: Localhost Test Instance
  title: Owncast Demo Server
  summary: "This is Gabe's localhost instance of Owncast."

  logo:
    small: /img/logo128.png
    large: /img/logo256.png

  tags:
    - software
    - music
    - animal crossing

  # https://github.com/gabek/owncast/blob/master/doc/configuration.md#customization
  # for full list of supported social links.  All optional.
  socialHandles:
    - platform: twitter
      url: http://twitter.com/owncast
    - platform: instagram
      url: http://instagram.biz/owncast
    - platform: facebook
      url: http://facebook.gov/owncast

videoSettings:
  # Change this value and keep it secure.  Treat it like a password to your live stream.
  streamingKey: abc123

  # Determine the bitrate of your stream variants.
  # See https://github.com/gabek/owncast/blob/master/doc/configuration.md#video-quality for details.
  streamQualities:
    - high:
      videoBitrate: 2000

    - medium:
      videoBitrate: 800


# s3:
#   enabled: true
#   endpoint: https://gabevideo.us-east-1.linodeobjects.com
#   accessKey: TM24VRAB57SLH72CS0XA
#   secret: zKpuJHRNLmOVnzh9gsoQHbRhpYAQt94xCb3Y7pou
#   region: us-east-1
#   bucket: gabevideo

s3:
  enabled: true
  endpoint: https://gabevideo.s3-us-west-2.amazonaws.com
  accessKey: AKIAZVILNW6ECSTICSPM
  secret: 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
  region: us-west-2
  bucket: gabevideo
  acl: public-read

# Enable YP to be listed in the Owncast directory and let people discover your instance.
yp:
  enabled: true
  ypServiceURL: https://owncast-yp-test.gabek.vercel.app
  instanceURL: http://localhost:8080
