name: Automated API tests

on:
  push:
    paths-ignore:
      - 'webroot/**'
      - pkged.go
  pull_request:
    paths-ignore:
      - 'webroot/**'
      - pkged.go
      
jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run API tests
        run: cd test/automated/api && ./run.sh

  