name: Automated end to end tests

on:
  push:
    # branches:
    #   - develop
  pull_request:
    branches: develop

jobs:
  API Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup and run
        run: cd test/automated/api && ./run.sh