name: Build web app
on:
  push:
    paths:
      - web/**

jobs:
  run:
    name: npm run build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd web && npm install --include=dev --force && npm run build
