name: lint
on:
  push:
  pull_request:

jobs:
  golangci:
    name: lint
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: golangci-lint command line arguments.
          args: --timeout 5m0s
          # Optional: working directory, useful for monorepos
          # working-directory: somedir
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
